list p=16f877a          ; SE DEFINE EL MICRO A UTILIZAR
#INCLUDE <P16F877A.INC> ; NOS PERMITE TRABAJAR LOS REGISTROS DE PROPOSITO ESPECIFICO CON NOMBRES

dato 	equ 0x20
dato1 	equ 0x21
dato2 	equ 0x22
X		EQU 0X23
Y 		EQU 0X24

	BSF		STATUS,5	;BANCO 1
	BCF		STATUS,6	
	CLRF	TRISB		;PUERTO B COMO SALIDAS
	BCF		STATUS,5    ;BANCO 0
	
	MOVLW	0X0F
	MOVWF	PORTB

END